name: Automerge
on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted
  check_suite:
    types:
      - completed
  status: {}
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: Automerge
        uses: "pascalgn/automerge-action@v0.12.0"
        env:
          MERGE_LABELS: ""
          MERGE_METHOD: "squash"
          MERGE_RETRY_SLEEP: 60000
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
