name: Deploy React and Firebase

on:
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cached Dependencies
        uses: ktmud/cached-dependencies@v1

      - name: Build
        run: npm run-script build

      - name: Deploy
        run: npx firebase deploy --token "${{ secrets.FIREBASE_TOKEN }}"
